### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by wifi75** [SebuZet/samsungrac#24]
@atxbyea on my log there is this error::
`
Traceback (most recent call last): File "/config/custom_components/climate_ip/samsung_2878.py", line 189, in send_socket_command sslSocket = self.socket File "/config/custom_components/climate_ip/samsung_2878.py", line 245, in socket self.create_connection() File "/config/custom_components/climate_ip/samsung_2878.py", line 234, in create_connection sslSocket.connect((cfg.host, cfg.port)) File "/usr/local/lib/python3.8/ssl.py", line 1342, in connect self._real_connect(addr, False) File "/usr/local/lib/python3.8/ssl.py", line 1329, in _real_connect super().connect(addr) OSError: [Errno 113] Host is unreachable`

why?

**Comment by kumy** [comment]
@wifi75 `[Errno 113] Host is unreachable` are you able to ping your AC ip?

**Comment by atxbyea** [comment]
yes, host unreachable means that whatever IP or hostname you entered is incorrect probably, what does your config look like ?

**Comment by wifi75** [comment]
Yess true. now it is ok.
