### ISSUE TITLE
SSL Error  2878 aircon

### ISSUE THREAD

**Issue by foughtgeoduck** [SebuZet/samsungrac#4]
Howdy,
I keep getting these error's
no controls or status are received by HASS

Sending command failed
Creating connecting failed!
and

Traceback (most recent call last):
  File "/config/custom_components/climate_ip/samsung_2878.py", line 180, in send_socket_command
    sslSocket.sendall(command.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'sendall'

[samsung_2878.txt](https://github.com/SebuZet/samsungrac/files/3323042/samsung_2878.txt)

If i disable the cert i get SSLv3 error

climate:
  - platform: climate_ip
    config_file: "samsung_2878.yaml"
    ip_address: "10.10.2.XXX"
    token: "d76b7f82-3d31-4635-89a6-2b0ad192xxxx"
    cert: "/config/custom_components/climate_ip/ac14k_m.pem" #set as '' to skip certificate verification
    mac: "BC:8C:CD:D6:XX:XX"
    friendly_name: "Hallway AC"
    debug: "true"

running HASSIO
python_version | 3.7.3
version | 0.94.4
virtualenv | false

Any help would be great
Thanks

**Comment by foughtgeoduck** [comment]
Here is some debug info

i have 2x AC's but they both get the same issue

`19-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] climate_ip: async setup platform
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Loading configuration file: /config/custom_components/climate_ip/samsung_2878_227.yaml
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] ip_address: 10.10.2.227
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] token: d76b7f82-3d31-4635-89a6-2b0ad192XXXX
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Validate properties: False (False)
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Configuration, host: 10.10.2.227:2878
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Configuration, token: d76b7f82-3d31-4635-89a6-2b0ad192XXXX
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Configuration, duid: BC8CCDD6D7BD
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Configuration, cert: /config/custom_components/climate_ip/ac14k_m.pem
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Executing params: {'duid': 'BC8CCDD6D7BD', 'token': 'd76b7f82-3d31-4635-89a6-2b0ad192XXX', 'host': '10.10.2.227', 'connection_template': '<Request Type="AuthToken"><User Token="{{token}}" /></Request>', 'value': None}
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Executing command: <Request Type="DeviceState" DUID="BC8CCDD6D7BD"></Request>

2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Getting socket connection
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Connection invalid, creating!
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Creating ssl context
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Setting up ciphers
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Setting up verify mode
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Setting up verify location: /config/custom_components/climate_ip/ac14k_m.pem
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Setting up load cert chain: /config/custom_components/climate_ip/ac14k_m.pem
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Wrapping socket
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Socket wrapped: True
2019-06-25 11:34:31 INFO (MainThread) [custom_components.climate_ip.climate] Connecting with 10.10.2.227:2878
2019-06-25 11:34:32 INFO (MainThread) [custom_components.climate_ip.climate] Response: DPLUG-1.6

2019-06-25 11:34:32 INFO (MainThread) [custom_components.climate_ip.climate] Response: <?xml version="1.0" encoding="utf-8" ?><Update Type="InvalidateAccount"/>

2019-06-25 11:34:32 INFO (MainThread) [custom_components.climate_ip.climate] Sending auth command: <Request Type="AuthToken"><User Token="d76b7f82-3d31-4635-89a6-2b0ad192XXXX" /></Request>

2019-06-25 11:34:32 INFO (MainThread) [custom_components.climate_ip.climate] Auth command sent
2019-06-25 11:34:34 WARNING (MainThread) [custom_components.climate_ip.climate] Socket timed out
2019-06-25 11:34:34 ERROR (MainThread) [custom_components.climate_ip.climate] Creating connecting failed!
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Sending command
2019-06-25 11:34:34 ERROR (MainThread) [custom_components.climate_ip.climate] Sending command failed
2019-06-25 11:34:34 ERROR (MainThread) [custom_components.climate_ip.climate] Traceback (most recent call last):
  File "/config/custom_components/climate_ip/samsung_2878.py", line 180, in send_socket_command
    sslSocket.sendall(command.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'sendall'

2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Retrying sending command...
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Getting socket connection
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Connection invalid, creating!
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Creating ssl context
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Setting up ciphers
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Setting up verify mode
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Setting up verify location: /config/custom_components/climate_ip/ac14k_m.pem
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Setting up load cert chain: /config/custom_components/climate_ip/ac14k_m.pem
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Wrapping socket
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Socket wrapped: True
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Connecting with 10.10.2.227:2878
2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Response: DPLUG-1.6

2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Response: <?xml version="1.0" encoding="utf-8" ?><Update Type="InvalidateAccount"/>

2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Sending auth command: <Request Type="AuthToken"><User Token="d76b7f82-3d31-4635-89a6-2b0ad192XXXX" /></Request>

2019-06-25 11:34:34 INFO (MainThread) [custom_components.climate_ip.climate] Auth command sent
2019-06-25 11:34:36 WARNING (MainThread) [custom_components.climate_ip.climate] Socket timed out
2019-06-25 11:34:36 ERROR (MainThread) [custom_components.climate_ip.climate] Creating connecting failed!
2019-06-25 11:34:36 INFO (MainThread) [custom_components.climate_ip.climate] Sending command
2019-06-25 11:34:36 ERROR (MainThread) [custom_components.climate_ip.climate] Sending command failed
2019-06-25 11:34:36 ERROR (MainThread) [custom_components.climate_ip.climate] Traceback (most recent call last):
  File "/config/custom_components/climate_ip/samsung_2878.py", line 180, in send_socket_command
    sslSocket.sendall(command.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'sendall'
`

**Comment by foughtgeoduck** [comment]
BUMP

**Comment by mttstt** [comment]
Same problem here with HA 94.1

Traceback (most recent call last): File "/config/custom_components/climate_ip/samsung_2878.py", line 180, in send_socket_command sslSocket.sendall(command.encode('utf-8')) AttributeError: 'NoneType' object has no attribute 'sendall'
0:27 custom_components/climate_ip/samsung_2878.py (ERROR) - message first occured at 0:17 and shows up 32 times
Sending command failed
0:27 custom_components/climate_ip/samsung_2878.py (ERROR) - message first occured at 0:17 and shows up 32 times
Creating connecting failed!
0:27 custom_components/climate_ip/samsung_2878.py (ERROR) - message first occured at 0:17 and shows up 32 times
Socket timed out
0:27 custom_components/climate_ip/samsung_2878.py (WARNING) - message first occured at 0:17 and shows up 32 times

**Comment by mttstt** [comment]
OK.
I solved with the master release.
Thanks

**Comment by foughtgeoduck** [comment]
didnt realise i wsa using DEV - resolved aswell - close please
